import {modelUrl} from './asset-path.js';
const root=modelUrl('encoder-leader-l1/');
export function encoderLinks(){return `<p class="panel-help"><a href="${root}READ-ME-FIRST.md" target="_blank">Encoder leader: BOM, wiring and assembly</a><br><a href="${root}P1S_ENCODER_CARTRIDGE_FIT.3mf" download>Test first: one encoder cartridge · 5 pieces</a><br><a href="${root}SO101-AS5600-LEADER-L1.zip" download>Download encoder leader kit · 37 printed pieces</a></p>`}
export function renderEncoderPlates(m,index,onSelect){
 const p=m.plates[index],leader=p.robot==='leader';
 document.querySelector('#panel-heading').textContent='P1S · complete prototype layouts';
 document.querySelector('#panel-body').innerHTML=`<p class="group-title">2 follower + 3 encoder leader plates</p><p class="panel-help">7 follower pieces + 37 leader pieces. Actual converted parts; no stock leader plates.</p><div class="plate-list">${m.plates.map((p,i)=>`<button data-encoder-plate="${i}" class="${i===index?'active':''}">${p.label}<small>${p.count} parts · ${p.height.toFixed(1)} mm high</small></button>`).join('')}</div><a class="download" href="/models/so101/${p.file}" download>Download geometry layout · 3MF</a><p class="notice">${leader?'Nominal encoder prototype. Print one cartridge set first; verify bearing fit, free rotation and magnet readings. Sliced layer review is still required.':'Follower full-plate print is not cleared: slicer clipping diagnostics remain unresolved.'} No tested payload or physical assembly claim.</p><p class="group-title">Starting print settings</p><p class="panel-help">P1S · 0.4 mm · PETG · 0.20 mm<br>4 walls · 25% gyroid · supports<br>12 mm spacing · 5 mm brim<br>Inspect small magnet and bearing pockets in the slicer.</p>${p.slicer?.gcode_summary?`<p class="panel-help">Slicer estimates:<br>${p.slicer.gcode_summary.map(s=>s.replace(/^; /,'')).join('<br>')}</p>`:''}${encoderLinks()}<p class="panel-help"><a href="/models/so101/follower-r3/READ-ME-FIRST.md" target="_blank">Follower BOM and assembly</a><br><a href="/models/so101/follower-r3/SO101-MG996R-R3-PROTOTYPE.zip" download>Download follower kit</a></p>`;
 document.querySelectorAll('[data-encoder-plate]').forEach(b=>b.onclick=()=>onSelect(+b.dataset.encoderPlate));
}
export function appendEncoderChecks(m){
 const e=m.encoder_leader,v=e.verification;
 document.querySelector('#checks-view').insertAdjacentHTML('afterbegin',`<h1>Passive encoder leader · L1</h1><p>Original SO-101 links, handle and trigger. Six AS5600 boards, six diametric magnets and twelve 688ZZ bearings replace the motors. 37 printed pieces on 3 P1S layouts.</p><div class="check-row good"><div>Nominal CAD interfaces<p>6/6 attachment checks pass. Cartridge rotation overlap: ${v.cartridge_rotation_max_overlap_mm3.toFixed(3)} mm³. PCB insertion clears. Magnet-to-chip gap: ${v.magnet_chip_gap_mm} mm.</p></div></div><div class="check-row pending"><div>Motion envelope is restricted<p>${v.tested_poses-v.failed_poses}/${v.tested_poses} sampled poses avoid internal overlaps; ${v.table_intersection_poses} intersect the table. The preview rejects detected collisions at requested poses. This does not validate the swept path or hardware.</p></div></div><div class="check-row pending"><div>Prototype, not physically validated<p>Print one cartridge first. Bearing fit, magnetic readings, wiring, fastener access, stiffness and powered follower control require bench tests. Firmware compiles; no hardware was flashed.</p></div></div>${encoderLinks()}<p><a href="${root}verification.json" target="_blank">Full encoder verification report</a></p>`);
 const pending=[...document.querySelectorAll('#checks-view p')].find(p=>p.textContent.includes('Encoder leader and electronics enclosure are not completed.'));
 if(pending)pending.textContent=pending.textContent.replace('Encoder leader and electronics enclosure are not completed.','Encoder leader CAD is provided above. Electronics enclosure remains unmodelled.');
}
