import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { STLLoader } from 'three/addons/loaders/STLLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { createIcons, icons } from 'lucide';
import './style.css';
import { clampJointAngles, applyJointAngles } from './kinematics.js';
import { frameBounds } from './view-layout.js';
import { addFitTestPlates } from './fit-test.js';
import { isR3, r3Notice, renderR3Plates, renderR3Checks, followerBelowTable } from './r3-ui.js';
import { createAssemblyGuard } from './assembly-guard.js';
import { encoderLinks, renderEncoderPlates, appendEncoderChecks } from './encoder-ui.js';

const $=s=>document.querySelector(s);
const studyView=new URLSearchParams(location.search).get('geometry')!=='original';
const icon=name=>`<i data-lucide="${name}"></i>`;
$('#app').innerHTML=`
<header class="topbar"><div class="brand"><svg class="brandmark" viewBox="0 0 32 32" fill="none"><path d="M6 26h20M10 24l4-12 10-6M14 12l10 9" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><circle cx="14" cy="12" r="3" fill="currentColor"/></svg>THENAR<small>ROBOT STUDIO</small></div><span class="rev">SO-101</span><div class="top-right"><span class="status-text">Original SO-101 · MG996R conversion pending</span><a class="download" href="/models/so101/SO101-originals.zip" download>${icon('download')}<span>Download original files</span></a></div></header>
<main class="workspace"><aside class="sidebar"><div class="side-head">Assembly explorer ${icon('layers')}</div><div class="side-section"><p class="side-label">VISIBLE ASSEMBLIES</p><button class="robot-button active" data-robot="both">${icon('boxes')}<span>Leader + follower<small>Original source geometry</small></span></button><button class="robot-button" data-robot="follower"><span class="robot-color"></span><span>Follower arm<small>Original STS3215 reference</small></span></button><button class="robot-button" data-robot="leader"><span class="robot-color leader"></span><span>SO-101 leader<small>Encoder conversion pending</small></span></button></div><div class="tree" id="tree"></div><div class="side-footer">Millimetres · exact source STLs<br>Actual CAD meshes in every view.</div></aside>
<nav class="tabs" aria-label="Workspace views"><button class="active" data-tab="assembly">${icon('box')}Assembly</button><button data-tab="plates">${icon('grid-2x2')}Print plates</button><button data-tab="checks">${icon('clipboard-check')}Parts & checks</button></nav>
<section class="canvas-wrap" aria-label="Interactive three-dimensional robot viewer"><div class="scene-title"><h1 id="scene-heading">The original SO-101.</h1><p id="scene-subtitle">Original meshes · MG996R fit not yet released</p></div><div class="view-tools"><button id="fit-view" title="Fit assembly" aria-label="Fit assembly">${icon('maximize')}</button><button id="front-view" title="Front view" aria-label="Front view">${icon('panel-top')}</button><button id="top-view" title="Top view" aria-label="Top view">${icon('square')}</button><button id="capture" title="Save view as PNG" aria-label="Save view as PNG">${icon('camera')}</button></div><div id="selected-tag" class="selected-tag hidden"></div><div class="legend"><span><b class="dot"></b>Follower</span><span><b class="dot blue"></b>Leader</span><span><b class="dot dark"></b>Purchased parts</span></div><span class="viewport-hint">Drag to orbit · Scroll to zoom</span><div class="loading" id="loading"><span id="load-label">Loading CAD assemblies…</span><progress value="0" max="100"></progress></div><div class="checks-view hidden" id="checks-view"></div></section>
<aside class="panel"><div class="panel-head" id="panel-heading">${icon('sliders-horizontal')} Joint controls</div><div class="panel-body" id="panel-body"></div></aside><footer class="footbar"><span id="footer-status">Preparing geometry</span><span>Geometric preview · no hardware connection</span></footer></main><div id="toast" class="toast hidden" role="status"></div>`;
$('.rev').outerHTML=`<select id="geometry-mode" aria-label="Geometry version" style="max-width:190px;background:#17253e;color:white;border:1px solid #738095;border-radius:4px;padding:7px"><option value="original">Original SO-101</option><option value="clearance">MG996R clearance study</option></select>`;
$('#geometry-mode option[value="clearance"]').textContent='MG996R follower · R3';
$('#geometry-mode').value=studyView?'clearance':'original';$('#geometry-mode').onchange=e=>{location.search=e.target.value==='clearance'?'?geometry=clearance':'?geometry=original'};
if(studyView){$('.status-text').textContent='Loading MG996R follower R3…';$('[data-robot="follower"] small').textContent='Original-derived MG996R conversion';$('.top-right .download').href='/models/so101/follower-r3/SO101-MG996R-R3-PROTOTYPE.zip';$('.top-right .download span').textContent='Download MG996R R3'}
const refreshIcons=()=>createIcons({icons});refreshIcons();
let manifest,report,fitReport,benchReport,motionCheck,activeTab='assembly',activeRobot='both',selected=null,angles=[],explosion=0,animate=false,transparent=false,showHardware=true,plateIndex=0;
let scene,camera,renderer,orbit,robotGroup,plateGroup,floor,grid;
const nodeMap={},partMeshes=[],geometries=new Map(),partMap=new Map(),materialMap=new Map();
let animationStart=0,assemblyGuard=null;
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.add('hidden'),3300)}
function material(p,robot){
 const key=p.id+robot;if(materialMap.has(key))return materialMap.get(key);
 let color=robot==='leader'?0x5585df:0xf2b845,metalness=.08,roughness=.48;
 if(p.kind==='hardware') {color=0x303848;roughness=.4;if(p.id.includes('bearing')||p.id.includes('horn')||p.id.includes('screw')){color=0xabb7c6;metalness=.8;roughness=.25}if(p.id.includes('pcb')||['esp32','pca9685','tca9548a'].includes(p.id))color=0x176f64;if(p.id.includes('magnet')){color=0x8d96a3;metalness=.85}}
 if(p.kind==='print'&&['servo_mount','encoder_mount','base','electronics_tray'].includes(p.id)){color=robot==='leader'?0x254570:0x304054}
 const mat=new THREE.MeshStandardMaterial({color,metalness,roughness});materialMap.set(key,mat);return mat;
}
function setupScene(){
 scene=new THREE.Scene();scene.background=new THREE.Color('#eef1f5');scene.fog=new THREE.Fog('#eef1f5',1800,4500);
 camera=new THREE.PerspectiveCamera(35,1,.5,8000);camera.up.set(0,0,1);camera.position.set(680,-1000,720);
 renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
 $('.canvas-wrap').prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Robot CAD viewport. Use the joint controls to move both assemblies.');
 const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();
 scene.add(new THREE.HemisphereLight(0xffffff,0x909cac,2));const sun=new THREE.DirectionalLight(0xffffff,3.2);sun.position.set(-300,-500,900);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-700;sun.shadow.camera.right=700;sun.shadow.camera.top=700;sun.shadow.camera.bottom=-700;sun.shadow.camera.far=2000;sun.shadow.normalBias=.5;scene.add(sun);
 floor=new THREE.Mesh(new THREE.PlaneGeometry(6000,6000),new THREE.MeshStandardMaterial({color:0xe8edf3,roughness:.9}));floor.position.z=-1;floor.receiveShadow=true;scene.add(floor);
 grid=new THREE.GridHelper(1600,64,0xc3cddb,0xd8dfe8);grid.rotation.x=Math.PI/2;grid.position.z=-.6;grid.material.transparent=true;grid.material.opacity=.52;scene.add(grid);
 robotGroup=new THREE.Group();plateGroup=new THREE.Group();scene.add(robotGroup,plateGroup);plateGroup.visible=false;
 orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.075;orbit.target.set(0,0,150);orbit.maxPolarAngle=Math.PI*.49;orbit.minDistance=70;orbit.maxDistance=7000;
 new ResizeObserver(()=>{const el=$('.canvas-wrap');camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);if(manifest&&partMeshes.length&&activeTab!=='checks')fitView()}).observe($('.canvas-wrap'));
 let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>4||activeTab!=='assembly')return;const b=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=ray.intersectObjects(partMeshes.filter(m=>m.visible&&nodeMap[m.userData.robot].visible),false)[0];if(hit)selectPart(hit.object.userData.part)});
 renderer.setAnimationLoop(t=>{if(animate&&activeTab==='assembly'){const s=(t-animationStart)/1000;const next=manifest.home.map((v,i)=>v+Math.sin(s*.65+i*.5)*[18,10,12,12,18,9][i]);if(!acceptPose(next))animate=false;syncSliders()}orbit.update();renderer.render(scene,camera)});
}
async function loadCAD(){
 const res=await fetch('/models/so101/'+(studyView?'study-manifest.json':'manifest.json'));if(!res.ok)throw new Error('CAD manifest could not be loaded.');const manifestText=await res.text();manifest=JSON.parse(manifestText);angles=[...manifest.home];
 try {fitReport=await(await fetch('/models/so101/fit-analysis.json')).json()}catch{fitReport=null}report=null;
 try {const r=await fetch('/models/so101/motion-verification.json');if(r.ok){motionCheck=await r.json();if(studyView){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(manifestText)))).map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==motionCheck.manifest_sha256)motionCheck=null}}}catch{motionCheck=null}
 if(!isR3(manifest))try {const r=await fetch('/models/so101/fit-test/verification.json');if(r.ok){benchReport=await r.json();addFitTestPlates(manifest,benchReport)}}catch{benchReport=null}
 if(isR3(manifest)){
  $('.status-text').textContent='MG996R follower R3 · nominal-fit prototype';
  $('.top-right .download').href='/models/so101/follower-r3/SO101-MG996R-R3-PROTOTYPE.zip';
  $('.top-right .download span').textContent='Download MG996R R3';
  $('[data-robot="follower"] small').textContent='7 converted printing units';
  $('[data-robot="both"] small').textContent='MG996R follower + stock leader';
  $('.side-footer').innerHTML='Millimetres · original-derived CAD<br>Nominal prototype · physical tests pending.';
 }
 if(manifest.encoder_leader){
  $('#geometry-mode option[value="clearance"]').textContent='MG996R + encoder leader';
  $('.status-text').textContent='MG996R follower + AS5600 encoder leader · prototypes';
  $('[data-robot="both"] small').textContent='Both converted assemblies';
  $('[data-robot="leader"] small').textContent='6 passive AS5600 encoder joints';
 }
 const loader=new STLLoader();let count=0;
 await Promise.all(manifest.parts.map(async p=>{partMap.set(p.id,p);const g=await loader.loadAsync('/models/so101/'+p.file);g.computeVertexNormals();geometries.set(p.id,g);$('progress').value=++count/manifest.parts.length*100}));
 for(const n of manifest.nodes){const g=new THREE.Group();g.position.fromArray(n.position);g.rotation.set(...n.rotation.map(THREE.MathUtils.degToRad));g.userData=n;nodeMap[n.id]=g;(n.parent?nodeMap[n.parent]:robotGroup).add(g)}
 for(const i of manifest.instances){const p=partMap.get(i.part),mesh=new THREE.Mesh(geometries.get(i.part),material(p,i.robot));mesh.position.fromArray(i.position);mesh.rotation.set(...i.rotation.map(THREE.MathUtils.degToRad));mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData={...i,originalPosition:[...i.position]};nodeMap[i.node].add(mesh);partMeshes.push(mesh)}
 updatePose();if(manifest.encoder_leader)assemblyGuard=createAssemblyGuard(partMeshes);
 buildTree();showPanel();fitView();$('#loading').classList.add('hidden');filterRobot(activeRobot);$('#footer-status').textContent=`${manifest.instances.length} components · ${manifest.parts.filter(p=>p.kind==='print').length} print-part meshes · mm`;
 window.studio={manifest,scene,renderer,camera,partMeshes,nodeMap,motionCheck,get angles(){return angles},setAngles(v){const ok=acceptPose(v);syncSliders();return ok},get activeTab(){return activeTab},get activeRobot(){return activeRobot},get plateIndex(){return plateIndex},selectPart,tab,fitView};
 if(new URLSearchParams(location.search).get('view')==='fit-test')tab('plates');
}
function updatePose(){angles=applyJointAngles(manifest.nodes,nodeMap,angles,manifest.limits);scene.updateMatrixWorld(true)}
function acceptPose(next){
 const previous=[...angles];angles=clampJointAngles(next,manifest.limits);updatePose();
 if(assemblyGuard&&explosion===0){const hit=assemblyGuard();if(hit){angles=previous;updatePose();toast(`Pose blocked: ${hit.type==='table'?'table contact':hit.a+' / '+hit.b}`);return false;}}
 if(isR3(manifest)&&explosion===0&&followerBelowTable(partMeshes)){
  angles=previous;updatePose();toast('Pose blocked: the follower would enter the tabletop.');return false;
 }
 return true;
}
function fitView(direction){
 if(manifest?.encoder_leader&&activeTab==='assembly'){$('#scene-heading').textContent=activeRobot==='leader'?'AS5600 encoder leader · L1':activeRobot==='follower'?'MG996R follower · R3':'Follower + encoder leader';$('#scene-subtitle').textContent='Original-derived CAD · nominal prototypes · physical tests pending';}
 const group=activeTab==='plates'?plateGroup:robotGroup;const box=new THREE.Box3();group.traverse(o=>{if(o.isMesh&&o.visible){let ancestor=o.parent,visible=true;while(ancestor){if(!ancestor.visible)visible=false;ancestor=ancestor.parent}if(visible)box.expandByObject(o)}});
 frameBounds(camera,box,orbit.target,direction?.isVector3?direction:undefined);orbit.update();
}
function selectPart(id){selected=id;for(const m of partMeshes){if(!m.userData.baseMat)m.userData.baseMat=m.material;if(m.userData.part===id){m.material=m.userData.baseMat.clone();m.material.emissive.setHex(0x336dcc);m.material.emissiveIntensity=.26}else m.material=m.userData.baseMat;}document.querySelectorAll('.part-entry').forEach(e=>e.classList.toggle('active',e.dataset.part===id));$('#selected-tag').textContent=partMap.get(id).label;$('#selected-tag').classList.remove('hidden');if(activeTab==='assembly')showPanel()}
function buildTree(){
 const groups=isR3(manifest)?[
  {label:'Converted follower',kind:'print',open:true,parts:manifest.parts.filter(p=>p.kind==='print'&&p.quantity?.follower)},
  {label:manifest.encoder_leader?'Converted encoder leader':'Stock leader reference',kind:'print',open:false,parts:manifest.parts.filter(p=>p.kind==='print'&&p.quantity?.leader)},
  {label:'Purchased components',kind:'hardware',open:false,parts:manifest.parts.filter(p=>p.kind==='hardware')}
 ]:['print','hardware'].map(kind=>({label:kind==='print'?'Printed components':'Purchased components',kind,open:kind==='print',parts:manifest.parts.filter(p=>p.kind===kind)}));
 $('#tree').innerHTML=groups.map(g=>`<details ${g.open?'open':''}><summary>${g.label} <span style="color:#77869b">${g.parts.length}</span></summary>${g.parts.map(p=>`<button class="part-entry" data-part="${p.id}">${icon(g.kind==='print'?'box':'cpu')}<span>${p.label}</span></button>`).join('')}</details>`).join('');
 document.querySelectorAll('.part-entry').forEach(e=>e.onclick=()=>{tab('assembly');selectPart(e.dataset.part)});refreshIcons();
}
function showPanel(){
 if(manifest.encoder_leader&&activeTab==='checks'){
  $('#panel-heading').textContent='Build both prototypes';$('#panel-body').innerHTML=encoderLinks()+'<p class="panel-help"><a href="/models/so101/follower-r3/READ-ME-FIRST.md" target="_blank">Follower BOM and assembly</a></p><p class="notice">CAD and firmware checks do not replace physical fit and load testing. No payload rating.</p>';return;
 }
 if(isR3(manifest)&&activeTab==='checks'){
  $('#panel-heading').textContent='MG996R prototype · build notes';
  $('#panel-body').innerHTML='<p class="group-title">Print and bench-test R3</p><p class="panel-help">Use the seven joined printing units. The stock leader and its encoder conversion are separate from this follower kit.</p><a class="download" href="/models/so101/follower-r3/SO101-MG996R-R3-PROTOTYPE.zip" download>Download MG996R prototype</a><div class="divider"></div><a href="/models/so101/follower-r3/READ-ME-FIRST.md" target="_blank">BOM, assembly and test notes</a><p class="notice">Single-sided servo output support. No powered test or payload rating has been established.</p>';return;
 }
 if(activeTab==='assembly'){
 $('#panel-heading').innerHTML=icon('sliders-horizontal')+' Joint controls';
 $('#panel-body').innerHTML=`<p class="group-title">Move together</p><p class="panel-help">${studyView?'Provisional MG996R limits: 170° maximum span, not physically calibrated.':'Original SO-101 travel limits.'} Bases are ${manifest.display_base_spacing_mm} mm apart for display only. No hardware connection.</p><label class="toggle">Show<select id="robot-select" aria-label="Visible assembly"><option value="both">Both robots</option><option value="follower">Follower</option><option value="leader">Leader</option></select></label><div class="joint-sliders">${manifest.jointNames.map((name,i)=>`<div class="slider-group"><div class="slider-heading"><label for="j${i}">${name}</label><output id="o${i}">${angles[i].toFixed(0)}°</output></div><input id="j${i}" aria-label="${name}" type="range" min="${manifest.limits[i][0]}" max="${manifest.limits[i][1]}" step="0.1" value="${angles[i]}"><div class="range-ends"><span>${manifest.limits[i][0]}°</span><span>${manifest.limits[i][1]}°</span></div></div>`).join('')}</div><p class="notice">${studyView&&motionCheck?`${motionCheck.collisions.failed_sampled_poses}/${motionCheck.collisions.tested_poses} sampled poses have solid overlaps. NOT print-ready.`:studyView?'Collision verification pending. NOT print-ready.':'Original geometry reference; not an MG996R print release.'}</p>${studyView&&motionCheck?`<label class="toggle">Review pose<select id="review-pose" aria-label="Review sampled collision pose"><option value="">Select…</option>${motionCheck.collisions.poses.map((p,i)=>`<option value="${i}">${p.name} · ${p.positive_volume_overlaps.length} overlaps</option>`).join('')}</select></label>`:''}<div class="button-row"><button class="outline-button" id="play">${icon(animate?'pause':'play')}${animate?'Pause':'Kinematic demo'}</button><button class="outline-button" id="reset">${icon('rotate-ccw')}Reset</button></div><div class="divider"></div><div class="slider-heading"><label for="explode">Exploded assembly</label><output>${explosion.toFixed(0)}%</output></div><input type="range" id="explode" min="0" max="100" value="${explosion}"><label class="toggle">Purchased components<input id="hardware-toggle" type="checkbox" ${showHardware?'checked':''}></label><label class="toggle">Transparent printed parts<input id="transparent-toggle" type="checkbox" ${transparent?'checked':''}></label>${selected?partInfo(partMap.get(selected)):''}`;
 if(isR3(manifest))$('#panel-body .notice').textContent=r3Notice(motionCheck);
 if(manifest.encoder_leader){$('#panel-body').insertAdjacentHTML('afterbegin',encoderLinks());if($('#review-pose'))$('#review-pose').parentElement.firstChild.textContent='Follower report poses';}
 manifest.jointNames.forEach((_,i)=>$('#j'+i).oninput=e=>{animate=false;const next=[...angles];next[i]=+e.target.value;acceptPose(next);syncSliders();$('#play').innerHTML=icon('play')+'Kinematic demo';refreshIcons()});
 if($('#review-pose'))$('#review-pose').onchange=e=>{if(e.target.value==='')return;animate=false;explosion=0;applyExplosion();const p=motionCheck.collisions.poses[+e.target.value];const accepted=acceptPose(p.angles_degrees);syncSliders();fitView();if(accepted)toast(`${p.name}: ${p.positive_volume_overlaps.length} internal overlaps; see Parts & checks`);else e.target.value=''};
 $('#robot-select').value=activeRobot;$('#robot-select').onchange=e=>filterRobot(e.target.value);
 $('#play').onclick=()=>{animate=!animate;animationStart=performance.now();showPanel()};$('#reset').onclick=()=>{animate=false;angles=[...manifest.home];explosion=0;applyExplosion();updatePose();showPanel();fitView()};
 $('#explode').oninput=e=>{explosion=+e.target.value;e.target.previousElementSibling.querySelector('output').textContent=explosion+'%';applyExplosion()};
 $('#hardware-toggle').onchange=e=>{showHardware=e.target.checked;partMeshes.forEach(m=>m.visible=showHardware||partMap.get(m.userData.part).kind==='print')};
 $('#transparent-toggle').onchange=e=>{transparent=e.target.checked;for(const m of partMeshes)if(partMap.get(m.userData.part).kind==='print'){m.material.transparent=transparent;m.material.opacity=transparent?.3:1;m.material.depthWrite=!transparent}};
 }else if(activeTab==='plates'){
 if(manifest.encoder_leader){renderEncoderPlates(manifest,plateIndex,index=>{plateIndex=index;showPlate();showPanel()});return;}
 if(isR3(manifest)){renderR3Plates(manifest,plateIndex,index=>{plateIndex=index;showPlate();showPanel()});return;}
 const p=manifest.plates[plateIndex];$('#panel-heading').innerHTML=icon('printer')+' Bambu Lab P1S';
 $('#panel-body').innerHTML=`<p class="group-title">${p.fitTest?'Test one servo first':'Stock SO-101 reference'}</p><p class="panel-help">${p.fitTest?'Unpowered bench-fit prints. These test nominal MG996R dimensions; they do not approve the full arm.':'Untouched Ender layouts placed on a P1S bed. Stock STS3215 parts, not MG996R conversions.'}</p><div class="plate-list">${manifest.plates.map((x,i)=>`<button data-plate="${i}" class="${i===plateIndex?'active':''}">${x.label}<small>${x.count} parts · ${x.height.toFixed(1)} mm high</small></button>`).join('')}</div><a class="download plate-download" href="/models/so101/${p.file}" download>${icon('download')}Download this 3MF</a><div class="divider"></div><p class="group-title">Print setup</p><p class="panel-help">${p.fitTest?'PETG · Textured PEI<br>':''}0.4 mm nozzle · 0.20 mm layers<br>4 walls · 25% gyroid<br>Print by layer, not by object</p><p class="notice">${p.fitTest&&p.slicer?.gcode_present?p.slicer.gcode_summary.filter(s=>s.includes('total estimated time')||s.includes('weight')).map(s=>s.replace(/^; /,'')).join('<br>')+'<br>Slicer estimates only. Confirm your material and supports before printing.':p.fitTest?'Slicing not verified; inspect and slice in Bambu Studio.':'Stock geometry only. Do not print expecting MG996R compatibility.'}</p><p class="panel-help"><a href="/models/so101/FIT-TEST.md" target="_blank">Fit-test instructions and measurements</a><br><a href="/models/so101/BOM.md" target="_blank">Hardware BOM: owned / needed / pending</a></p><a href="/models/so101/fit-test/MG996R-BENCH-FIT-R1.zip" download>Download test STLs, STEP and instructions</a>`;
 document.querySelectorAll('[data-plate]').forEach(b=>b.onclick=()=>{plateIndex=+b.dataset.plate;showPlate();showPanel()});
 }else{
 $('#panel-heading').innerHTML=icon('file-check-2')+' Build information';$('#panel-body').innerHTML=`<p class="group-title">Original source revision</p><p class="panel-help">14 exact individual STLs, two original combined layouts and matching upstream STEP files. No generated replacement arm is used here.</p><a class="download" href="/models/so101/SO101-originals.zip" download>${icon('download')}Original source bundle</a><div class="divider"></div><p class="group-title">Before a full print</p><p class="panel-help">1. Calibrate the usable travel of your 180° servos.<br>2. Measure the supplied horns and mounting tabs.<br>3. Resolve the rejected wrist motor holder.<br>4. Finish attachment and strength checks before printing.</p><p class="notice">No physical robot has been tested. Mesh checks, joint animation and successful slicing cannot certify payload, strength or real servo travel.</p><div class="divider"></div><a href="/models/so101/README.md" target="_blank">Conversion status and required measurements</a>`;
 }if(activeTab!=='plates')$('#panel-body').insertAdjacentHTML('afterbegin',isR3(manifest)?'<p class="panel-help"><a href="?geometry=clearance&view=fit-test">View MG996R printing plates</a><br><a href="/models/so101/follower-r3/READ-ME-FIRST.md" target="_blank">Prototype BOM and assembly notes</a></p>':`<p class="panel-help"><a href="?geometry=clearance&view=fit-test">Print the quick MG996R fit test</a><br><a href="/models/so101/BOM.md" target="_blank">Follower + leader hardware BOM</a></p>`);refreshIcons();
}
function partInfo(p){return `<div class="divider"></div><div class="parts-info"><h3>${p.label}</h3>${p.kind==='print'?'3D printed component':'Purchased component · reference envelope'}<br>${p.bounds.map(x=>x.toFixed(1)).join(' × ')} mm<br>${p.quantity?`Follower × ${p.quantity.follower} · Leader × ${p.quantity.leader}`:'Fit-check part'}<p>${p.notes||''}</p><div class="part-actions"><a href="/models/so101/${p.file}" download>Download ${p.kind==='print'?'print':'reference'} STL</a></div></div>`}
function syncSliders(){angles.forEach((v,i)=>{const el=$('#j'+i);if(el)el.value=v;const o=$('#o'+i);if(o)o.textContent=v.toFixed(0)+'°'})}
function applyExplosion(){if(manifest.revision.startsWith('SO101-')){for(const m of partMeshes){m.position.fromArray(m.userData.originalPosition);m.position.z+=explosion*(partMap.get(m.userData.part).kind==='hardware'?-.4:.3);}return;}for(const m of partMeshes){m.position.fromArray(m.userData.originalPosition);const p=m.userData.part;if(['servo_hub','encoder_hub'].includes(p))m.position.z+=explosion*.5;else if(p==='bearing_6805')m.position.z+=explosion*.22;else if(['servo_mount','encoder_mount'].includes(p))m.position.z-=explosion*.3;else if(p==='mg996r')m.position.z-=explosion*.48;else if(['upper_link','fore_link','wrist_bracket','axis_bracket','moving_finger','leader_trigger'].includes(p))m.position.z+=explosion*.8;}scene.updateMatrixWorld(true)}
function filterRobot(robot){activeRobot=robot;nodeMap.follower.visible=robot!=='leader';nodeMap.leader.visible=robot!=='follower';document.querySelectorAll('[data-robot]').forEach(e=>e.classList.toggle('active',e.dataset.robot===robot));$('#scene-heading').textContent=robot==='both'?'The original SO-101.':robot==='follower'?'SO-101 follower':'SO-101 leader';$('#scene-subtitle').textContent=robot==='both'?'Original meshes · MG996R fit not yet released':robot==='follower'?'Upstream joint datums · stock servo reference':'Original leader parts · handle/trigger pose provisional';if(studyView){$('#scene-heading').textContent='MG996R clearance study';$('#scene-subtitle').textContent='Localized cuts only · rejected wrist mount · DO NOT PRINT'}if(isR3(manifest)){$('#scene-heading').textContent=robot==='leader'?'Leader · source reference':'MG996R follower · R3';$('#scene-subtitle').textContent=robot==='both'?'Converted follower + reference leader · 800 mm display spacing':robot==='follower'?'7 original-derived printing units · nominal-fit prototype':'Encoder conversion not completed'}if($('#robot-select'))$('#robot-select').value=robot;fitView()}
function showPlate(){
 while(plateGroup.children.length){const c=plateGroup.children[0];plateGroup.remove(c);if(c.userData.disposable){c.geometry?.dispose();c.material?.dispose()}}
 const plate=manifest.plates[plateIndex],bed=new THREE.Mesh(new THREE.BoxGeometry(256,256,3),new THREE.MeshStandardMaterial({color:0x293444,roughness:.85}));bed.position.set(128,128,-1.5);bed.receiveShadow=true;bed.userData.disposable=true;plateGroup.add(bed);
 const reserved=new THREE.Mesh(new THREE.PlaneGeometry(256,30),new THREE.MeshBasicMaterial({color:0xa75b2b,transparent:true,opacity:.3,side:THREE.DoubleSide}));reserved.position.set(128,15,.1);reserved.userData.disposable=true;plateGroup.add(reserved);
 for(const e of plate.entries){const mesh=new THREE.Mesh(geometries.get(e.part),material(partMap.get(e.part),plate.robot));mesh.applyMatrix4(new THREE.Matrix4().fromArray(e.matrix));mesh.castShadow=true;mesh.receiveShadow=true;plateGroup.add(mesh)}
 $('#scene-heading').textContent=plate.label;$('#scene-subtitle').textContent=plate.fitTest?`${plate.count} test parts · unpowered bench fit only`:`${plate.count} mesh shells · original layout, not MG996R converted`;fitView();
 if(plate.prototype)$('#scene-subtitle').textContent=`${plate.count} ${plate.robot==='leader'?'encoder leader':'MG996R follower'} printing pieces · PETG prototype`;
}
function showChecks(){
 if(isR3(manifest)){renderR3Checks(manifest,motionCheck);if(manifest.encoder_leader)appendEncoderChecks(manifest);return;}
 const pass=manifest.parts.every(p=>p.watertight),collisions=studyView?motionCheck?.collisions:null;
 $('#checks-view').innerHTML=`<h1>Source verified. Conversion pending.</h1><p>${studyView?'Original-part clearance drafts and nominal MG996R envelopes are shown.':'The original source meshes are unchanged; stock STS3215 references are shown.'} This is not an MG996R-compatible print release.</p>
 <div class="check-row ${pass?'good':'pending'}">${icon(pass?'circle-check':'circle-alert')}<div>Mesh closure check<p>${manifest.parts.filter(p=>p.kind==='print').length} print-part meshes; ${pass?'all exported meshes are watertight':'some draft meshes have open seams; see fit analysis. NOT printable as a kit'}.</p></div></div>
 <div class="check-row good">${icon('circle-check')}<div>P1S plate layout<p>Two stock layouts and ${manifest.plates.filter(p=>p.fitTest).length} alternative fit-test layouts. Only the separate bench tests have been sliced; stock layouts are not converted arm prints.</p></div></div>
 ${benchReport?`<div class="check-row good">${icon('circle-check')}<div>Wrist-holder bench prototype<p>Original-derived holder with tab ledges and insertion opening. Three closed test meshes; nominal servo intersection ${benchReport.nominal_servo_intersection_mm3} mm³. Separate prototype, not installed in the failing arm assembly.</p><a href="?geometry=clearance&view=fit-test">View test plate</a> · <a href="/models/so101/FIT-TEST.md" target="_blank">Test procedure</a> · <a href="/models/so101/BOM.md" target="_blank">Hardware BOM</a></div></div>`:''}
 <div class="check-row ${collisions?.home_interferences===0?'good':'pending'}">${icon(collisions?.home_interferences===0?'circle-check':'circle-alert')}<div>Assembly interference check<p>${collisions?`${collisions.home_interferences} solid overlap candidates at home. ${collisions.failed_sampled_poses}/${collisions.tested_poses} sampled poses have overlaps. Full motion envelope is ${collisions.full_envelope_passed?'clear in sampled poses':'not certified'}.`:'Original follower datums imported; leader handle/trigger placement is provisional. MG996R interference and attachment checks are not passed.'}</p></div></div>
 <div class="check-row ${report?.slicer?.status==='passed'?'good':'pending'}">${icon('printer')}<div>Bambu Studio slicing<p>${report?.slicer?.summary||'Awaiting slicer verification; no invented print-time estimate.'}</p></div></div>
 <div class="check-row pending">${icon('circle-alert')}<div>Physical fit, payload and temperature<p>${report?.torque?.summary||'Awaiting servo measurements and bench testing. No payload rating has been established.'}</p></div></div>
 <div class="check-row pending">${icon('circle-alert')}<div>Servo travel: user confirmed 180°<p>You confirmed 180° travel. The MG996R view is capped at 170° span per joint, with narrower provisional limits where appropriate. Actual horn indexing and travel still need calibration. <a href="https://www.amazon.in/dp/B0F2TKPB95" target="_blank" rel="noreferrer">Inspect listing</a></p></div></div><div class="check-row pending">${icon('circle-alert')}<div>Original-part MG996R clearance study<p>${fitReport?fitReport.parts.filter(p=>p.status.startsWith('REJECTED')).map(p=>p.part+': cut produces '+p.solid_count+' solids').join('; '):'Study report unavailable'}. Mounting fasteners, opposite-side support and strength are NOT verified.</p><a href="/models/so101/fit-analysis.json" target="_blank">Per-part report</a> · <a href="/models/so101/MG996R-clearance-study-NOT-PRINT-RELEASE.zip" download>Download inspection drafts — not print release</a></div></div><div class="check-row pending">${icon('scan-line')}<div>MG996R sampled motion report<p>${motionCheck?`${motionCheck.collisions.tested_poses} poses: home, neutral, single-joint extrema/midpoints, 16 demo samples and 8 combined poses. Positive-volume overlaps are unresolved; circular horn envelopes are conservative. Continuous swept motion, leader encoders, loads and physical fit are NOT certified.`:'Report pending or stale for this geometry.'}</p><a href="/models/so101/motion-verification.json" target="_blank">Download full collision report</a></div></div><h2 style="font-size:18px;margin-top:28px">Parts list</h2><input class="search" id="part-search" placeholder="Filter parts…" aria-label="Filter parts"><table><thead><tr><th>Component</th><th>Type</th><th>Follower</th><th>Leader</th><th>STL</th></tr></thead><tbody id="bom">${manifest.parts.filter(p=>p.kind!=='plate').map(p=>`<tr data-name="${p.label.toLowerCase()}"><td>${p.label}</td><td>${p.kind==='print'?'Print':'Buy'}</td><td>${p.quantity?.follower||'—'}</td><td>${p.quantity?.leader||'—'}</td><td><a href="/models/so101/${p.file}" download>Get</a></td></tr>`).join('')}</tbody></table>`;
 const testNames=new Set(manifest.parts.filter(p=>p.kind==='test').map(p=>p.label.toLowerCase()));
 $('#bom').querySelectorAll('tr').forEach(tr=>{if(testNames.has(tr.dataset.name))tr.children[1].textContent='Test print'});
 $('#part-search').oninput=e=>$('#bom').querySelectorAll('tr').forEach(tr=>tr.hidden=!tr.dataset.name.includes(e.target.value.toLowerCase()));refreshIcons();
}
function tab(id){activeTab=id;animate=false;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));robotGroup.visible=id==='assembly';plateGroup.visible=id==='plates';$('#checks-view').classList.toggle('hidden',id!=='checks');$('.scene-title').classList.toggle('hidden',id==='checks');$('.view-tools').classList.toggle('hidden',id==='checks');$('.legend').classList.toggle('hidden',id!=='assembly');$('#selected-tag').classList.add('hidden');if(id==='plates')showPlate();if(id==='checks')showChecks();if(id==='assembly')filterRobot(activeRobot);showPanel()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>manifest&&tab(b.dataset.tab));document.querySelectorAll('[data-robot]').forEach(b=>b.onclick=()=>{if(manifest){tab('assembly');filterRobot(b.dataset.robot)}});
$('#fit-view').onclick=()=>fitView();$('#front-view').onclick=()=>fitView(new THREE.Vector3(0,-1,.04));$('#top-view').onclick=()=>fitView(new THREE.Vector3(0,-.001,1));$('#capture').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download='thenar-'+activeTab+'.png';a.href=renderer.domElement.toDataURL('image/png');a.click();toast('View saved as PNG')};
try{setupScene();loadCAD().catch(e=>{$('#load-label').textContent=e.message;toast('Could not load CAD. Reload to try again.');console.error(e)})}catch(e){$('#load-label').textContent='WebGL is unavailable. Enable hardware acceleration to view the robot.';console.error(e)}
